### ISSUE TITLE
Make Logman handle multiple loggers

### ISSUE THREAD

**Issue by bmarkons** [renderedtext/logman#4]
@shiroyasha Do you have in mind to support multiple loggers? Similar thing we have with multi_logger gem.

**Comment by shiroyasha** [comment]
Yes, the support is ready.

It works like this:

``` ruby
$api_logger = Logman.new
$build_api = Logman.new
```

If you want to log to a file:

``` ruby
$logger = Logman.new(:logger => Logger.new("/tmp/a.txt"))
```

If you want to log to use Rails logger, you can do it via:

``` ruby
$logger = Logman.new(:logger => Rails.logger)
```

This way, Logman is not concerned about where the output goes (STDOUT, file, Rails.logger), it is only concerned with how the log will be formatted.

The output of the log is left for the user to define.

Should we change this behavior?

**Comment by bmarkons** [comment]
Basically I wanted to avoid using multi_logger gem, because you can't pass STDOUT to the `MultiLogger#add_logger`. Though I get your idea to make Logman as logger agnostic.

**Comment by bmarkons** [comment]
I think we should support passing multiple instances of Logger's to the Logman instance. Sometimes you want to output your logs to the both STDOUT and file (or multiple files).

**Comment by shiroyasha** [comment]
Closing. Stale.
